/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NodeType = "file" | "function" | "class" | "interface" | "export";
export type EdgeType = "import" | "export" | "extends" | "implements" | "calls";

export interface GraphModuleSchema {
  data: GraphData;
  viewport: ViewportState;
  interaction: InteractionState;
  [k: string]: unknown;
}
export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
  metadata: GraphMetadata;
  [k: string]: unknown;
}
export interface GraphNode {
  id: string;
  label: string;
  filePath: string;
  type: NodeType;
  x: number;
  y: number;
  size: number;
  [k: string]: unknown;
}
export interface GraphEdge {
  source: string;
  target: string;
  type: EdgeType;
  weight: number;
  [k: string]: unknown;
}
export interface GraphMetadata {
  totalNodes: number;
  totalEdges: number;
  rootDirectory: string;
  generatedAt: number;
  [k: string]: unknown;
}
export interface ViewportState {
  zoom: number;
  pan: Point;
  [k: string]: unknown;
}
export interface Point {
  x: number;
  y: number;
  [k: string]: unknown;
}
export interface InteractionState {
  selectedNodeId?: string | null;
  hoveredNodeId?: string | null;
  [k: string]: unknown;
}
